accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name="login"),
    path('logout', auth_views.LogoutView.as_view(), name="logout"),
    path('signup', views.SignUp.as_view(), name="signup")
]

groups/urls.py
from django.urls import path
from groups.views import GroupCreateView,GroupDetailView,GroupListView

app_name = "groups"

urlpatterns = [
    path('', GroupListView.as_view(), name="group_list"),
    path('new/', GroupCreateView.as_view(), name="group_create"),
    path('<slug>/', GroupDetailView.as_view(), name="group_details"),
]

posts/urls.py
from django.urls import path
from posts.views import PostListView,PostCreateView,PostDetailView,PostDeleteView,UserPosts

app_name = "posts"

urlpatterns = [
    path('', PostListView.as_view(), name="post_list"),
    path('by/<username>', UserPosts.as_view(), name="user_posts"),
    path('new/', PostCreateView.as_view(), name="post_create"),
    path('by/<username>/<int:pk>', PostDetailView.as_view(), name="post_details"),
    path('delete/<int:pk>', PostDeleteView.as_view(), name="post_delete"),
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls',namespace='groups')),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)
    

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse

# Instantiating the user model to the logged in user in the current session
User = get_user_model()

# Template tagging
register = template.library

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True, default='')
    members = models.ManyToManyField(User, through="GroupMember")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:group_details", kwargs={'slug':self.slug})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
    

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="user_groups", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")
    

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from groups.models import Group
from django.urls import reverse

# Instantiating the user session
User = get_user_model()

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts_by_user", on_delete=models.CASCADE)
    group = models.ForeignKey(Group, related_name="post_group", on_delete=models.CASCADE, null=True, blank=True)
    post_create_date = models.DateTimeField(auto_now=True)
    post_text = models.TextField(blank=False)

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:post_details", kwargs={"username": self.user.username, "pk":self.pk})

    def __str__(self):
        return self.post_text
    
    class Meta:
        ordering=('-post_create_date',)
        unique_together = ['user','post_text']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

#Create your forms here
class UserSignupForm(UserCreationForm):
    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Display Name"
        self.fields['email'].label = "Email Address"

accounts/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView
from . import forms
from django.urls import reverse_lazy, reverse


# Create your views here.
class SignUp(SuccessMessageMixin, CreateView):
    template_name = 'registration/signup.html'
    form_class = forms.UserSignupForm
    success_url = reverse_lazy('accounts:signup')
    success_message = "Sign up was successful"

groups/views.py
from django.shortcuts import render
from django.views.generic import CreateView,TemplateView,ListView,DetailView
from groups.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator

# Create your views here.
class GroupCreateView(CreateView, LoginRequiredMixin):
    model = Group
    fields = ('name', 'description')

class GroupListView(ListView):
    model = Group
    template_name = "groups/group_list.html"
    paginate_by = 3
    queryset = Group.objects.all()

class GroupDetailView(DetailView):
    model = Group
    template_name = "groups/group_details.html"
    context_object_name = 'group_details'
    paginate_by = 2
    queryset = Group.objects.all()

posts/views.py
from django.shortcuts import render
from posts.models import Post
from django.views.generic import TemplateView,ListView,CreateView,DeleteView,DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.http import Http404
from django.contrib import messages
from django.core.paginator import Paginator

# Using Select Related Mixins: This is a kind of performance booster, in the sense that the database only has to be hit once for a queryset with connections to a foreignkey
# Then subsequent hits will be on the already called query set since the table would have been prepopulated from the initial call
from braces.views import SelectRelatedMixin

# Instatiating the user for the current session
User = get_user_model()

# Create your views here.
class PostListView(SelectRelatedMixin, ListView):
    model = Post
    template_name = "posts/post_list.html"
    select_related = ('user', 'group')
    paginate_by = 3
    queryset = Post.objects.all()


class UserPosts(LoginRequiredMixin, SelectRelatedMixin, ListView):
    model = Post
    template_name = "posts/user_posts_list.html"
    paginate_by = 2
    queryset = Post.objects.all()

    def get_queryset(self):
        try:
            self.user_post = User.objects.prefetch_related("posts_by_user").get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.user_post.posts_by_user.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_post"] = self.user_post 
        return context
    

class PostDetailView(SelectRelatedMixin, DetailView):
    model = Post
    template_name = "posts/post_details.html"
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset =  super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))
    

class PostCreateView(CreateView, SelectRelatedMixin, LoginRequiredMixin):
    model = Post
    fields = ('group', 'post_text')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class PostDeleteView(DeleteView,SelectRelatedMixin, LoginRequiredMixin):
    model = Post
    success_url = reverse_lazy('posts:post_list')
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "POST DELETED")
        return super().delete(request, *args, **kwargs)
    

socialmedia/views.py
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name = 'index.html'

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
        <!-- Master CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'socialmedia/css/master.css' %}">

        <!-- Font Awesome Script -->
        <script src="https://kit.fontawesome.com/5ab6d1b1f5.js"></script>

        {% block title %}
        {% endblock title %}

        <!-- Navigation bars from Bootstrap -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark text-info">
            <a class="navbar-brand" href="{% url 'index' %}">Stars</a>
            <a class="nav-item nav-link active text-info" href="/admin">Admin</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link text-info" href="{% url 'posts:post_list' %}">Post<span class="sr-only">(current)</span></a>
                        <a class="nav-item nav-link text-info" href="{% url 'groups:group_list' %}">Groups</a>
                        <a class="nav-item nav-link text-info" href="{% url 'groups:group_create' %}">Create Group</a>
                        <a class="nav-item nav-link text-info" href="{% url 'accounts:logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link text-info" href="{% url 'groups:group_list' %}">Groups</a>
                        <a class="nav-item nav-link text-info" href="{% url 'accounts:login' %}">Log In</a>
                        <a class="nav-item nav-link text-info" href="{% url 'accounts:signup' %}">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </head>

    <body>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>

        <canvas id="canvas"></canvas>

        <!--Master JS File-->
        <script src="{% static 'socialmedia/js/master.js' %}" type="text/javascript"></script>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/groups/group_details.html
{% extends 'groups/groups_base.html' %}

{% block title %}
    <title>Groups - StarSocial</title>
{% endblock title %}

{% block pregroup %}
    <div class="col-4">
    <br><br>
        <h2>{{ group_details.name }}</h2><hr>
        <h5>Member Count: {{ group_details.members.count }}</h5>
    </div>
{% endblock pregroup %}

{% block group_content %}
    <div class="col-8">
    <br><br>
        {% for post in group_details.post_group.all %}
            <h5>{{ post.post_text|linebreaksbr }}
                <small>
                {% if user.is_authenticated and post.user == user %}
                    <a class="btn btn-danger btn-sm" href="{% url 'posts:post_delete' pk=post.pk %}"><i class="fas fa-trash"></i></a>
                {% endif %}
                </small>
            </h5>
            <small>Posted: {{ post.post_create_date }} | {{ post.group }} | by: @{{ post.user }}</small><hr class="bg-light">
        {% empty %}
            <h4>No posts in this group</h4>
        {% endfor %}
        {% if user.is_authenticated %}
            <a href="{% url 'posts:post_create' %}" class="btn btn-info btn-sm">New Post <i class="fas fa-plus-circle"></i></a>
        {% endif %}
    </div>
{% endblock group_content %}

{% block postgroup %}
{% if is_paginated %}
    <nav aria-label="Page navigation example"><br>
        <ul class="pagination pagination-sm justify-content-end">
            <li class="page-item"><a class="page-link text-info" href="?page=1"><<<</a></li>
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
            <li class="page-item"><a class="page-link bg-info text-light" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.paginator.num_pages }}">>>></a></li>
        </ul>
    </nav>
{% endif %}
{% endblock postgroup %}

templates/groups/group_form.html
{% extends 'groups/groups_base.html' %}
{% load bootstrap4 %}

{% block title %}
    <title>Groups - StarSocial</title>
{% endblock title %}

{% block group_content %}
<div class='col-12'>
    <div align="center"><br>
    {% if user.is_authenticated %}
        <h3>Create A Group</h3><hr>
        <form method="POST" action="{% url 'groups:group_create' %}">
            {% csrf_token %}
            {% bootstrap_form form%}
            <input type="submit" class="btn btn-block btn-info" value="Create">
        </form>
    {% else %}
        <h3>Access Denied</h3>
    {% endif %}
    </div>
</div>
{% endblock group_content %}

templates/groups/group_list.html
{% extends 'groups/groups_base.html' %}

{% block title %}
    <title>Groups - StarSocial</title>
{% endblock title %}

{% block pregroup %}
    <div class="col-4">
        <br><br>
        {% if user.is_authenticated %}
            <h5>Welcome back<p><a class="text-info" href="{% url 'posts:user_posts' username=user.username %}">@{{ user.username }}</a></p></h5><hr>
            <h5>Groups</h5>
            <p>Welcome to the Groups Page. Select a group with a shared interest</p>
            <a href="{% url 'groups:group_create' %}" class="btn btn-info btn-sm"><i class="fas fa-plus-circle"></i> Create New Group</a>
        {% else %}
            <h5>Groups</h5>
            <p>Welcome to the Groups Page. Please <a href="{% url 'accounts:login' %}">Login</a> to get full access.</p>
        {% endif %}
    </div>
{% endblock pregroup %}

{% block group_content %}
    <div class="col-8">
        <br><br>
        {% for group in group_list %}
        <div class="list-group">
            <a href="{% url 'groups:group_details' slug=group.slug %}" class="list-group-item list-group-item-action">
                <h5 class="card-title">{{ group.name }}</h5><hr>
                <p class="card-text">{{ group.description}}</p>
                <div class="d-flex justify-content-around">
                    <small><span class="badge badge-secondary">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</small>
                    <small><span class="badge badge-secondary">{{ group.post_group.count }}</span> post{{ group.post_group.count|pluralize }}</small>
                </div>
            </a>
        </div>
        {% empty %}
            <div align="center">
                <h4>No groups at the moment</h4>
            </div>
        {% endfor %}
    </div>
{% endblock group_content %}

{% block postgroup %}
{% if is_paginated %}
    <nav aria-label="Page navigation example"><br>
        <ul class="pagination pagination-sm justify-content-end">
            <li class="page-item"><a class="page-link text-info" href="?page=1"><<<</a></li>
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
            <li class="page-item"><a class="page-link bg-info text-light" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.paginator.num_pages }}">>>></a></li>
        </ul>
    </nav>
{% endif %}
{% endblock postgroup %}

templates/groups/groups_base.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            {% block pregroup %}{% endblock pregroup %}
            {% block group_content %}{% endblock group_content %}
        </div>
        {% block postgroup %}{% endblock postgroup %}
    </div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Home - StarSocial</title>
{% endblock title %}

{% block content %}
    <div align="center"><br><br>
        <h1>Welcome to Star Social!!!</h1>
        <p>Your one stop hub for all information regarding the stars and the planets</p>
        {% if user.is_authenticated %}
            <h4><a class="text-info" href="{% url 'posts:user_posts' username=user.username %}">@{{ user.username }}</a></h4>
            <p>You can create or join groups, make posts and see all other post from other groups</p>
            <small>Have Fun!!!</small>
        {% else %}
            <a href="{% url 'accounts:signup' %}" class="text-info">Sign Up to get Started</a><br>
            <span>Already a member? <a href-"{% url 'accounts:login' %}" class="text-info">Login</a></span>
        {% endif %}

    </div>
{% endblock content %}

templates/posts/post_confirm_delete.html
{% extends "posts/posts_base.html" %}

{% block post_content %}
<div class="col-2"><p></p></div>
<div class="col-12">
    <div align="center"><br><br>
        <h3>Are you sure you want to delete this post?</h3>

        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
            <a href="{% url 'posts:post_details' username=user.username pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/post_details.html
{% extends 'posts/posts_base.html' %}

{% block prepost %}
    <div class="col-12"><br><br>
        <h3>{{ post.post_text|linebreaksbr }}</h1><hr class="text-info bg-light">
        <small>Posted by: {{ post.user }} | On: {{ post.post_create_date }} <strong> {{ post.group }}</strong>
            {% if user.is_authenticated and post.user == user %}
                <a class="btn btn-danger btn-sm" href="{% url 'posts:post_delete' pk=post.pk %}"><i class="fas fa-trash"></i></a>
            {% endif %}
        </small>
    </div>
{% endblock prepost %}

templates/posts/post_form.html
{% extends 'posts/posts_base.html' %}
{% load bootstrap4 %}

{% block post_content %}
    <div class="col-2"><p></p></div>
    <div class="col-8">
        <div align="center"><br><br>
        {% if user.is_authenticated %}
            <h5>New Post</h5><hr>
            <form method="POST" action="{% url 'posts:post_create' %}">
            {% csrf_token %}
                {% bootstrap_form form%}
                <input type="submit" class="btn btn-info btn-block" value="Create">
            </form>
        {% else %}
            <h3>Access Denied</h3>
        {% endif %}
        </div>
    </div>
    <div class="col-2"><p></p></div>
{% endblock post_content %}

templates/posts/post_list.html
{% extends 'posts/posts_base.html' %}

{% block prepost %}
    <div class="col-2"><p></p></div>
    <div class="col-8">
    <br><br>
        {% for post in post_list %}
            <div class="card text-white bg-dark mb-3">
                <ul style="color:black;" class="list-group bg-dark">
                    <a class="list-group-item list-group-item-action" href="{% url 'posts:post_details' username=post.user pk=post.pk %}"><h6>{{ post.post_text|truncatewords:7 }}</h6></a>
                    <li class="list-group-item">@{{ post.user }} | {{ post.post_create_date }} | {{ post.group }}</li>
                </ul>
            </div><br>
        {% empty %}
            <h3>No posts has been made yet</h3>
        {% endfor %}
    </div>
    <div class="col-2"><p></p></div>
{% endblock prepost %}

{% block post_post %}
{% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination pagination-sm justify-content-center">
            <li class="page-item"><a class="page-link text-info" href="?page=1"><<<</a></li>
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
            <li class="page-item"><a class="page-link bg-info text-light" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.paginator.num_pages }}">>>></a></li>
        </ul>
    </nav>
{% endif %}
{% endblock post_post %}

templates/posts/posts_base.html
{% extends 'base.html' %}

{% block title %}
    <title>Posts - StarSocial</title>
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            {% block prepost %}
            {% endblock prepost %}
            {% block post_content %}
            {% endblock post_content %}
        </div>
        {% block post_post %}
        {% endblock post_post %}
    </div>
{% endblock content %}

templates/posts/user_posts_list.html
{% extends 'posts/posts_base.html' %}

{% block prepost %}
    <div class="col-4">
    <br><br>
        <h2>@{{ user_post.username }}</h2>
        <h6>Your Post History</h6>
    </div>
{% endblock prepost %}

{% block post_content %}
    <div class="col-8">
    <br><br>
        {% for post in post_list %}
            <h5>{{ post.post_text|linebreaksbr|truncatewords:50 }}
            <small>
            {% if user.is_authenticated and post.user == user %}
                <a class="btn btn-danger btn-sm" href="{% url 'posts:post_delete' pk=post.pk %}"><i class="fas fa-trash"></i></a>
            {% endif %}
            </small></h5>
            <small>Posted: {{ post.post_create_date }} | <a class="text-info" href="{% url 'groups:group_details' slug=post.group.slug %}">{{ post.group }}</a></small><hr>
        {% empty %}
            <h4>You have not made a post yet!</h4>
        {% endfor %}
        <a href="{% url 'posts:post_create' %}" class="btn btn-info btn-sm">New Post <i class="fas fa-plus-circle"></i></a>
    </div>
{% endblock post_content %}

{% block post_post %}
{% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination pagination-sm justify-content-end">
            <li class="page-item"><a class="page-link text-info" href="?page=1"><<<</a></li>
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
            <li class="page-item"><a class="page-link bg-info text-light" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
            <li class="page-item"><a class="page-link text-info" href="?page={{ page_obj.paginator.num_pages }}">>>></a></li>
        </ul>
    </nav>
{% endif %}
{% endblock post_post %}